### ISSUE TITLE
[BUG] Minecraft will crash when too many sounds play at once

### ISSUE THREAD

**Issue by epifeny** [John200410/rusherhack-issues#1065]
Describe the bug

```
java.util.ConcurrentModificationException
    at com.google.common.collect.HashBiMap$Itr.hasNext(HashBiMap.java:401)
    at net.minecraft.client.audio.SoundManager.func_148605_d(SoundManager.java:252)
    at net.minecraft.client.audio.SoundHandler.func_73660_a(SoundHandler.java:293)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1858)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

To Reproduce
Add portal block to search and enabled `Render` -> `Search` -> `Blocks` -> `Sound` ; and then try and enter into a range of approx 200 portals that you create. In-game scenario this happened in was 2b2t around nether 0x0.

Other mods
NA

Expected behavior
NA

Screenshots
NA

Additional context
This was discussed in Discord DM with John since I sent him the crash report there.

**Comment by jennifer-uwu** [comment]
duplicate

**Comment by epifeny** [comment]
> 
> 
> duplicate

Of which other bug was this a duplicate of?

**Comment by John200410** [comment]
Unable to find duplicates

**Comment by John200410** [comment]
This has been fixed in the next update.
