### ISSUE TITLE
[BUG] Rusherhack installer crashes on M1 Mac

### ISSUE THREAD

**Issue by azarovalex** [John200410/rusherhack-issues#1193]
**Describe the bug**
Running RusherInstaller.jar will result in a crash during the login process.

**To Reproduce**
1. Open RusherInstaller.jar on an arm64 (M1) Mac
2. Enter credentials
3. Press "Login"
4. It will crash

**Other mods**
List other forge mods you are using (if any): Not applicable, this is crash in the installer itself.

**Expected behavior**
Installer shouldn't crash.

**Additional context**
Logs: 
```
java.util.concurrent.ExecutionException: java.lang.UnsatisfiedLinkError: /private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp: dlopen(/private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp: no matching architecture in universal wrapper
	/private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp: no matching architecture in universal wrapper
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
	at rusherhack.$$k.a(Unknown Source)
	at rusherhack.$$g.done($$g.java:86)
	at java.desktop/javax.swing.SwingWorker$5.run(SwingWorker.java:750)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(SwingWorker.java:848)
	at java.desktop/sun.swing.AccumulativeRunnable.run(AccumulativeRunnable.java:112)
	at java.desktop/javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(SwingWorker.java:858)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp: dlopen(/private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp, 1): no suitable image found.  Did find:
	/private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp: no matching architecture in universal wrapper
	/private/var/folders/9c/fmnc10rn5833pdbt4q8sv7qm0000gp/T/jna--413162705/jna433264253806313735.tmp: no matching architecture in universal wrapper
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
	at com.sun.jna.Native.<clinit>(Native.java:190)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)
	at com.sun.jna.PointerType.<init>(PointerType.java:36)
	at com.sun.jna.ptr.ByReference.<init>(ByReference.java:41)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:33)
	at com.sun.jna.ptr.IntByReference.<init>(IntByReference.java:29)
	at oshi.rusheredition.util.platform.mac.SysctlUtil.sysctl(SysctlUtil.java:95)
	at oshi.rusheredition.software.os.mac.MacOSVersionInfoEx.<init>(MacOSVersionInfoEx.java:39)
	at oshi.rusheredition.software.os.mac.MacOperatingSystem.<init>(MacOperatingSystem.java:68)
	at oshi.rusheredition.SystemInfo.getOperatingSystem(SystemInfo.java:98)
	at rusherhack.$$k.a(Unknown Source)
	at rusherhack.$$R.$$z($$R.java:29)
	at rusherhack.$$k.a(Unknown Source)
	at rusherhack.$$g.$$l($$g.java:44)
	at rusherhack.$$k.a(Unknown Source)
	at rusherhack.$$g.doInBackground($$g.java:38)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)```

**Comment by John200410** [comment]
Are you using the latest version of MacOS? There were bugs with Rosetta emulation but Apple has fixed most of them

**Comment by azarovalex** [comment]
I'm on 11.6.1, which is the latest in the _11.x_ branch, however not as latest as the macOS 12.1. Unfortunately, I am not able to update to the latest macOS version due to personal reasons.

On a good note, I was able to solve the issue by installing x64 JDK and running it under Rosetta, previously I had a native arm64 JDK. (Both are from [Oracle](https://www.oracle.com/java/technologies/downloads/#jdk17-mac))

**Comment by John200410** [comment]
Alright, glad you solved the issue
