### ISSUE TITLE
[BUG]  crash on login

### ISSUE THREAD

**Issue by Crystallinqq** [John200410/rusherhack-issues#452]
**Describe the bug**
java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.renderer.ActiveRenderInfo.func_178806_a(ActiveRenderInfo.java:57)
	at net.minecraft.client.renderer.ActiveRenderInfo.func_186703_a(ActiveRenderInfo.java:68)
	at net.minecraft.client.renderer.EntityRenderer.func_78481_a(EntityRenderer.java:502)
	at net.minecraft.client.renderer.EntityRenderer.func_78476_b(EntityRenderer.java:753)
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1439)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**To Reproduce**
join game
**Other mods**
List other forge mods you are using (if any):
rushers hacking
**Expected behavior**
join the game
**Screenshots**
![image](https://user-images.githubusercontent.com/11377481/107721493-c6c56f00-6caa-11eb-9d1c-24faccd6a7f9.png)
this is what it looks like before it crashes. :(

**Additional context**
@John200410 HELP HELP HELP

**Comment by Novola** [comment]
i think it gets fixed when john stops buying cp and unbans me :/

**Comment by ElliotOnTop** [comment]
he needs to stop looking at lolis

**Comment by Crystallinqq** [comment]
PLEASE HELP 
@John200410 PLEASE HELP 
@John200410 PLEASE HELP 
@John200410

**Comment by John200410** [comment]
Make sure you are using the latest version of forge.

**Comment by Aholicknight** [comment]
![msedge_iOaalHPxTo](https://user-images.githubusercontent.com/7843719/107891689-de3c6c00-6ee5-11eb-977a-c5fddc5c9463.png)
